medstore_management/medstore/urls.py
from django.urls import path
from medstore import views 

app_name ='medstore'

urlpatterns = [
    path('',views.index, name='index'),

    path('new_bill/',views.new_bill, name='new_bill'),
    path('sales_report/',views.sales_report, name='sales_report'),

#dealer 
    path('view_dealer/',views.view_dealer, name='view_dealer'),
    path('add_dealer/',views.add_dealer, name='add_dealer'),
    path('dealerforminsert/',views.dealerforminsert, name='dealerforminsert'),
    path('dealerformupdate/<int:foo>',views.dealerformupdate, name='dealerformupdate'),
    path('dealerformview/<int:foo>',views.dealerformview, name='dealerformview'),
    path('dealerformdelete/<int:foo>',views.dealerformdelete, name='dealerformdelete'),

#cust 
    path('view_cust/',views.view_cust, name='view_cust'),
    path('add_cust/',views.add_cust, name='add_cust'),
    path('custforminsert/',views.custforminsert, name='custforminsert'),
    path('custformupdate/<int:foo>',views.custformupdate, name='custformupdate'),
    path('custformview/<int:foo>',views.custformview, name='custformview'),
    path('custformdelete/<int:foo>',views.custformdelete, name='custformdelete'),

#med
    path('view_med/',views.view_med, name='view_med'),
    path('add_med/',views.add_med, name='add_med'),
    path('dealer_med/',views.dealer_med, name='dealer_med'),
    path('medicineforminsert/',views.medicineforminsert, name='medicineforminsert'),
    path('medformupdate/<int:foo>',views.medformupdate, name='medformupdate'),
    path('medformview/<int:foo>',views.medformview, name='medformview'),
    path('medformdelete/<int:foo>',views.medformdelete, name='medformdelete'),

    
    path('view_purchase/',views.view_purchase, name='view_purchase'),
    path('add_purchase/',views.add_purchase, name='add_purchase'),

#emp
    path('view_emp/',views.view_emp, name='view_emp'),
    path('add_emp/',views.add_emp, name='add_emp'),
    path('empforminsert/',views.empforminsert, name='empforminsert'),
    path('empformupdate/<int:foo>',views.empformupdate, name='empformupdate'),
    path('empformview/<int:foo>',views.empformview, name='empformview'),
    path('empformdelete/<int:foo>',views.empformdelete, name='empformdelete'),

    
]

medstore_management/medstore_management/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/',admin.site.urls),
    path('', include('medstore.urls')),
]

medstore_management/medstore/models.py
from django.db import models

# Create your models here.
class Dealer(models.Model):
    dname = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    phn_no = models.BigIntegerField(unique=True)
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.dname

class Employee(models.Model):
    fname = models.CharField(max_length=30)
    lname = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    sal = models.CharField(max_length=20)
    phn_no = models.BigIntegerField(unique=True)

    def __str__(self):
        return self.email

class Customer(models.Model):
    fname = models.CharField(max_length=30)
    lname = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    phn_no = models.BigIntegerField(unique=True)

    def __str__(self):
        return self.email

class Medicine(models.Model):
    m_name = models.CharField(max_length=30)  
    dname = models.CharField(max_length=30)
    price = models.IntegerField()
    mrp = models.IntegerField()

    def __str__(self):
        return self.m_name
                

medstore_management/medstore/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['cust_id', 'fname', 'lname', 'phn_no', 'address', 'med_name', 'qty']

medstore_management/medstore/views.py
from .models import Dealer
from .models import Employee
from .models import Customer
from .models import Medicine
# from .models import Purchase
from django.shortcuts import render
from django.db import IntegrityError
from django.http import HttpResponse


# Create your views here.
# index 01 -------------------------------------------
def index(request):
    return render(request, 'index.html')
###---------------------------------------------------


###------------sales --------------------------------
# new bill  02
def new_bill(request):    
    return render(request, 'new_bill.html')

# sales report  03  --------------------------------
def sales_report(request):    
    return render(request, 'view_sales_report.html')
###---------------------------------------------------


###------------DEALER -------------------------------

def view_dealer(request):
    dealer = Dealer.objects.all()
    dict = {"dealer": dealer}  
    print(dealer)   
    return render(request, 'view_dealer.html', dict)

#add dealer 05
def add_dealer(request):
    dict = {'add': True, }    
    return render(request, 'add_dealer.html', dict)


def dealerforminsert(request):
    try:
        dealer = Dealer()
        dealer.dname = request.POST['dname']
        dealer.address = request.POST['address']
        dealer.phn_no = request.POST['pno']
        dealer.email = request.POST['email']
        dealer.save()
    except IntegrityError:
        return HttpResponse("<script>window.alert('already exists!!!');</script>")
    return HttpResponse("<script>window.alert('SUCCESSFULLY ADDED!!!');window.location.href='/view_dealer/'</script>")



def dealerformupdate(request, foo):
    try:
        dealer = Dealer.objects.get(pk=foo)
        dealer.dname = request.POST['dname']
        dealer.address = request.POST['address']
        dealer.phn_no = request.POST['pno']
        dealer.email = request.POST['email']
        {'dealer':dealer}
        dealer.save()
    except IntegrityError:
        return HttpResponse("<script>window.alert('already exists!!!');</script>")
    return HttpResponse("<script>window.alert('SUCCESSFULLY UPDATED!!!');window.location.href='/view_dealer/'</script>")



def dealerformview(request, foo):
    dealer = Dealer.objects.get(pk=foo)
    dict = {'dealer': dealer}
    return render(request, 'add_dealer.html', dict)


def dealerformdelete(request, foo):
    dealer = Dealer.objects.get(pk=foo)
    dealer.delete()
    return HttpResponse("<script>window.alert('deleted!');window.location.href='/view_dealer/'</script>")

###------------customer-------------------------------
#view customer 12
def view_cust(request):
    cust = Customer.objects.all()
    dict = {"cust": cust}
    return render(request, 'view_customer.html',dict)

#add customer13
def add_cust(request):
    dict = {'add': True, }    
    return render(request, 'add_customer.html',dict)

def custforminsert(request):
    try:
        cust = Customer()
        cust.fname = request.POST['fname']
        cust.lname = request.POST['lname']
        cust.address = request.POST['address']
        cust.phn_no = request.POST['pno']
        cust.email = request.POST['email']
        cust.save()
    except IntegrityError:
        return HttpResponse("<script>window.alert('already exists!!!');window.location.href='/view_cust/'</script>")
    return HttpResponse("<script>window.alert('SUCCESSFULLY ADDED!!!');window.location.href='/view_cust/'</script>")



def custformupdate(request, foo):
    try:
        cust = Customer.objects.get(pk=foo)
        cust.fname = request.POST['fname']
        cust.lname = request.POST['lname']
        cust.address = request.POST['address']
        cust.phn_no = request.POST['pno']
        cust.email = request.POST['email']
        cust.save()
    except IntegrityError:
        return HttpResponse("<script>window.alert('already exists!!!');window.location.href='/view_cust/'</script>")
    return HttpResponse("<script>window.alert('SUCCESSFULLY UPDATED!!!');window.location.href='/view_cust/'</script>")

def custformview(request, foo):
    cust = Customer.objects.get(pk=foo)
    dict = {'cust': cust}
    return render(request, 'add_customer.html', dict)

def custformdelete(request, foo):
    cust = Customer.objects.get(pk=foo)
    cust.delete()
    return HttpResponse("<script>window.alert('deleted!');window.location.href='/view_cust/'</script>")


###---------------------------------------------------



###------------medicine-------------------------------

def view_med(request):
    med = Medicine.objects.all()
    dict = {"med": med}
    return render(request, 'view_med.html',dict)

#add MEDICINE
def add_med(request):
    dict = {'add': True, }    
    dealer = Dealer.objects.all()
    print(dealer)   
    return render(request, 'add_med.html',dict)

## ## ## ## ## ## 

def dealer_med(request):
    dealer = dealer.objects.all()
    return render(request, 'add_med.html',{'dealer':dealer}
)

def medicineforminsert(request):
    try:
        med = Medicine()
        med.m_name = request.POST['m_name']
        med.dname = request.POST['dname']
        med.price = request.POST['price']
        med.mrp = request.POST['mrp']
        med.save()
    except IntegrityError:
        return HttpResponse("<script>window.alert('already exists!!!');</script>")
    return render(request, 'view_med.html')


def medformupdate(request, foo):
    try:
        med = Medicine.objects.get(pk=foo)
        med.m_name = request.POST['m_name']
        med.dname = request.POST['dname']
        med.price = request.POST['price']
        med.mrp = request.POST['mrp']
        med.save()
    except IntegrityError:
        return HttpResponse("<script>window.alert('already exists!!!');</script>")
    return HttpResponse("<script>window.alert('SUCCESSFULLY UPDATED!!!');window.location.href='/view_med/'</script>")

def medformview(request, foo):
    med = Medicine.objects.get(pk=foo)
    dict = {'med': med}
    return render(request, 'add_med.html', dict)

def medformdelete(request, foo):
    med = Medicine.objects.get(pk=foo)
    med.delete()
    return HttpResponse("<script>window.alert('deleted!');window.location.href='/view_med/'</script>")

###---------------------------------------------------


###------------purchase -------------------------------
#view purchase   08
def view_purchase(request):    
    return render(request, 'view_purchase.html')

#add purchase  09
def add_purchase(request):    
    return render(request, 'add_purchase.html')
###---------------------------------------------------




###------------EMPLOYEE-------------------------------
#view EMPLOYEE 12
def view_emp(request):
    emp = Employee.objects.all()
    dict = {"emp": emp}
    return render(request, 'view_emp.html',dict)

#add EMPLOYEE
def add_emp(request):
    dict = {'add': True, }    
    return render(request, 'add_emp.html',dict)

def empforminsert(request):
    try:
        emp = Employee()
        emp.fname = request.POST['fname']
        emp.lname = request.POST['lname']
        emp.address = request.POST['address']
        emp.email = request.POST['email']
        emp.sal = request.POST['sal']
        emp.phn_no = request.POST['pno']
        emp.save()
    except IntegrityError:
        return HttpResponse("<script>window.alert('hehe already exists!!!');</script>")
    return HttpResponse("<script>window.alert('added!');window.location.href='/view_emp/'</script>")


def empformupdate(request, foo):
    try:
        emp = Employee()
        emp.fname = request.POST['fname']
        emp.lname = request.POST['lname']
        emp.address = request.POST['address']
        emp.email = request.POST['email']
        emp.sal = request.POST['sal']
        emp.phn_no = request.POST['pno']
        emp.save()
    except IntegrityError:
        return HttpResponse("<script>window.alert('up already exists!!!');</script>")
    return render(request, 'view_emp.html')

def empformview(request, foo):
    emp = Employee.objects.get(pk=foo)
    dict = {'emp': emp}
    return render(request, '123_emp.html', dict)

def empformdelete(request, foo):
    emp = Employee.objects.get(pk=foo)
    emp.delete()
    return HttpResponse("<script>window.alert('deleted!');window.location.href='/view_emp/'</script>")


###---------------------------------------------------





medstore_management/medstore/templates/add_customer.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>medstore_management</title>

        
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

            

  
</head>

<body>
    
    <link rel="stylesheet" href="{% static '/js/add_cust.css' %}">
 
    
    <div class="container-fluid mt-3" >
          
        <div class="container-fluid mt-3 row" id="main_menu">
                
            <!-- sales_button -->                
        
            <div class="btn btn-outline-secondary dropdown col" data-bs-toggle="dropdown">   
                <div class="dropdown col">
                    <img src="{% static '/js/sales.png' %}" alt="sales">   
                    <h3 >SALES</h3>   
                </div>        
                        
                <ul class="dropdown-content">
                    <li class="dropdown-item"><a href="{% url 'medstore:new_bill' %}"> NEW BILL </a></li>
                    <li class="dropdown-item"><a href="{% url 'medstore:sales_report' %}">SALES REPORT</a></li>
                </ul>
            </div>

            <!-- dealer_button -->  
            
            <div class="btn btn-outline-secondary dropdown col" data-bs-toggle="dropdown">   
                <div class="dropdown col">
                    <img src="{% static '/js/dealer.png' %}" alt="dealer">                   
                    <h3>DEALER</h3>                       
                </div>        
                    
                <ul class="dropdown-content">
                    <li><a class="dropdown-item" href="{% url 'medstore:view_dealer' %}">VIEW DEALER</a></li>
                    <li><a class="dropdown-item" href="{% url 'medstore:add_dealer' %}">ADD DEALER</a></li>                    
                </ul>
            
            </div>

            <!-- medicine_button -->

            <div class="btn btn-outline-secondary dropdown col" data-bs-toggle="dropdown">   
                <div class="dropdown col">
                    <img src="{% static '/js/medicine.png' %}" alt="medicine">   
                    <h3>MEDICINE</h3>                        
                </div>        
                    
                <ul class="dropdown-content">
                    <a class="dropdown-item" href="{% url 'medstore:view_med' %}"> VIEW MEDICINE</a>
                    <a class="dropdown-item" href="{% url 'medstore:add_med' %}">ADD MEDICINE</a>                       
                </ul>
            </div>
                
            <!-- purchase_button -->

            <div class="btn btn-outline-secondary dropdown col" data-bs-toggle="dropdown">   
                <div class="dropdown col">
                    <img src="{% static '/js/purchase.png' %}" alt="PURCHASE">   
                    <h3 >PURCHASE</h3>                            
                </div>        
                    
                <ul class="dropdown-content">
                    <a class="dropdown-item" href="{% url 'medstore:view_purchase' %}"> VIEW PURCHASE</a>
                    <a class="dropdown-item" href="{% url 'medstore:add_purchase' %}">ADD PURCHASE</a>                     
                </ul>
            </div>

              
            <!-- employee_button -->      

            <div class="btn btn-outline-secondary dropdown col" data-bs-toggle="dropdown">   
                <div class="dropdown col">
                    <img src="{% static '/js/employee.png' %}" alt="employee">   
                    <h3>EMPLOYEE</h3>                           
                </div>        
                    
                <ul class="dropdown-content">                
                    <a class="dropdown-item" href="{% url 'medstore:view_emp' %}">VIEW EMPLOYEE</a>
                    <a class="dropdown-item" href="{% url 'medstore:add_emp' %}">ADD EMPLOYEE</a>
                </ul>
            </div>
                    
                   
            <!-- customers_button -->
            
            <div class="btn btn-outline-secondary dropdown col" data-bs-toggle="dropdown">   

                <div class="dropdown col">
                    <img src="{% static '/js/customer.png' %}" alt="customers">   
                    <h3 >CUSTOMERS</h3>                      
                </div>        
                    
                <ul class="dropdown-content">                    
                    <a class="dropdown-item" href="{% url 'medstore:view_cust' %}">VIEW CUSTOMERS</a>
                    <a class="dropdown-item" href="{% url 'medstore:add_cust' %}">ADD CUSTOMERS</a>                        
                </ul>
            </div>
                                
        </div>
        
    </div>
    <div class="container" id="add_cust">
        <div class="col-md-2"></div>
        <div >
            <div >
                <h1>
                    {% if add %}
                    Add customer Details
                    {% else %}
                    Update customer Details
                    {% endif %}
                </h1>
            </div>
            <div >
                <!--------------------------------------------------------0001--------------------------------------->
                {% if cust %}
                <form action="/custformupdate/{{ cust.id }}" method="post">
                    {% csrf_token %}
                    <div>
                        <div>
                            <label for="fname" class="form-control-label"> First Name:</label>
                        </div>
                        <div >
                            <input type="text" name="fname" class="form-control" id="fname" placeholder="Dealer Name"
                                value="{{ cust.fname }}" required />
                        </div>
                    </div>

                    <div>
                        <div>
                            <label for="lname" class="form-control-label">Last Name:</label>
                        </div>
                        <div >
                            <input type="text" name="lname" class="form-control" id="lname" placeholder="Last Name"
                                value="{{ cust.lname }}" />
                        </div>
                    </div>
                    
                    <div>
                        <div>
                            <label for="address" class="form-control-label">Address:</label>
                        </div>
                        <div >
                            <input type="text" class="form-control" id="address" placeholder="Address" name="address"
                                value="{{ cust.address }}" />
                        </div>
                    </div>
                    
                    <div>                        
                        <div>
                            <label for="phn_no" class="form-control-label">Phone Number:</label>
                        </div>
                        <div >
                            <input type="text" name="pno" class="form-control" id="phn_no" placeholder="Contact Number"
                            value="{{ cust.phn_no }}" required />
                        </div>
                    </div>
                    
                    <div>
                        <div>
                            <label for="email" class="form-control-label ">Email:</label>
                        </div>
                        
                        <div>
                            <input type="text" name="email" class="form-control" id="email" placeholder="Email"
                            value="{{ cust.email }}" />
                        </div>
                        
                    </div>
                    
                    <!-- button -->
                    <div class="col" id="buttoncustom">
                       
                        <div>
                            <button type="submit" class="btn btn-outline-secondary">
                                <a href="{% url 'medstore:index' %}">Cancel</a></button>
                        </div>

                        <div>
                            <button type="submit" class="btn btn-outline-success">
                                {% if add %}
                                Add Customer details
                                {% else %}
                                Update Customer details
                                {% endif %}
                            </button>
                        </div>
                        
                        <div>

                            <button type="submit" class="delbut btn btn-outline-danger">
                         
                                <a href="/custformdelete/{{ cust.id }}">Delete Record {{ foo.id }}</a>
                             
                            </button>
                        </div>

                    </div>
                </form>

                <!----------------------------------------00002-------->
                {% else %}

                <form action="{% url 'medstore:custforminsert' %}" method="post">
                    {% csrf_token %}
                    
                    <div class="row padtop15">
                        <div class="col-md-3 padtop5">
                            <label for="fname" class="form-control-label">First Name:</label>
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" name="fname" class="form-control" id="fname" placeholder="Customer Name"
                                value="" required />
                        </div>
                    </div>

                    <div class="row padtop5">
                        <div class="col-md-3 padtop5">
                            <label for="lname" class="form-control-label">Last Name:</label>
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control" id="lname" placeholder="Last Name" name="lname" />
                        </div>
                    </div>

                    <div class="row padtop5">
                        <div class="col-md-3 padtop5">
                            <label for="address" class="form-control-label">Address:</label>
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control" id="address" placeholder="Address" name="address" />
                        </div>
                    </div>

                    <div class="row padtop5">
                        <div class="col-md-3 ">
                            <label for="phn_no" class="form-control-label  ">Phone Number:</label>
                        </div>
                        <div class="col-md-6">
                            <input type="text" name="pno" class="form-control" id="phn_no" placeholder="Contact Number"
                                required />
                        </div>
                    </div>
                    
                    <div class="row padtop10">
                        <div class="col-md-3 padtop5">
                            <label for="email" class="form-control-label ">Email:</label>
                        </div>
                        <div class="col-md-6">
                            <input type="text" name="email" class="form-control" id="email" placeholder="Email" />
                        </div>
                    </div>

        <!-- button -->

                    <div class="col" id="buttoncustom2">
                        <div class="col-md-3"></div>                        
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-outline-secondary">
                                <a href="{% url 'medstore:index' %}">Cancel</a>
                            </button>
                        </div>

                        <div class="col-md-2 padtop25">
                            <button type="submit" class="btn btn-outline-success">
                                {% if add %}
                                Add Record
                                {% else %}
                                Update Record
                                {% endif %}
                            </button>
                        </div>
                    </div>
                
                </form>

                {% endif %}
            </div>

        </div>

    </div>

<!---------------------->

</body>    